// All hashing/signing uses the Web Crypto API, which is natively available
// in the Workers runtime — no `nodejs_compat` flag or Buffer polyfills needed.

function toHex(buffer: ArrayBuffer): string {
  return Array.from(new Uint8Array(buffer))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

export async function sha256Hex(input: string): Promise<string> {
  const data = new TextEncoder().encode(input);
  const digest = await crypto.subtle.digest("SHA-256", data);
  return toHex(digest);
}

/** Keyed hash (HMAC-SHA256) — used so a raw DB leak of hashes alone isn't enough to forge tokens. */
export async function hmacSha256Hex(secret: string, message: string): Promise<string> {
  const key = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"]
  );
  const sig = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(message));
  return toHex(sig);
}

export function timingSafeEqual(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let result = 0;
  for (let i = 0; i < a.length; i++) {
    result |= a.charCodeAt(i) ^ b.charCodeAt(i);
  }
  return result === 0;
}

export function randomToken(bytes = 32): string {
  const arr = new Uint8Array(bytes);
  crypto.getRandomValues(arr);
  return toHex(arr.buffer);
}

export function randomUuid(): string {
  return crypto.randomUUID();
}

/** 6-digit numeric OTP, generated with crypto.getRandomValues (not Math.random). */
export function generateOtp(length = 6): string {
  const digits = new Uint32Array(length);
  crypto.getRandomValues(digits);
  return Array.from(digits, (n) => (n % 10).toString()).join("");
}

// ---------------------------------------------------------------------------
// Password hashing (admin auth only — students never have a password, they
// use email OTP / Google). PBKDF2-SHA256 via the same Web Crypto API used
// everywhere else in this file, so no extra dependency and no
// `nodejs_compat` flag is needed in the Worker.
//
// Stored format: `pbkdf2:<iterations>:<saltHex>:<hashHex>`
// scripts/create-admin.mjs produces hashes in this exact format using
// Node's `node:crypto` webcrypto (API-compatible with the Workers runtime),
// so a hash generated by the bootstrap script verifies correctly here.
// ---------------------------------------------------------------------------

const PBKDF2_ITERATIONS = 100_000;
const PBKDF2_HASH_BYTES = 32;

function hexToBytes(hex: string): Uint8Array {
  const bytes = new Uint8Array(hex.length / 2);
  for (let i = 0; i < bytes.length; i++) {
    bytes[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  }
  return bytes;
}

async function pbkdf2Hex(
  password: string,
  saltBytes: Uint8Array,
  iterations: number
): Promise<string> {
  const keyMaterial = await crypto.subtle.importKey(
    "raw",
    new TextEncoder().encode(password),
    { name: "PBKDF2" },
    false,
    ["deriveBits"]
  );
  const derived = await crypto.subtle.deriveBits(
    { name: "PBKDF2", salt: saltBytes, iterations, hash: "SHA-256" },
    keyMaterial,
    PBKDF2_HASH_BYTES * 8
  );
  return toHex(derived);
}

/** Hashes a plaintext password for storage in `admins.password_hash`. */
export async function hashPassword(password: string): Promise<string> {
  const saltBytes = crypto.getRandomValues(new Uint8Array(16));
  const hashHex = await pbkdf2Hex(password, saltBytes, PBKDF2_ITERATIONS);
  return `pbkdf2:${PBKDF2_ITERATIONS}:${toHex(saltBytes.buffer)}:${hashHex}`;
}

/** Verifies a plaintext password against a stored `pbkdf2:...` hash. Constant-time comparison of the final hash. */
export async function verifyPassword(password: string, stored: string): Promise<boolean> {
  const parts = stored.split(":");
  if (parts.length !== 4 || parts[0] !== "pbkdf2") return false;
  const iterations = Number(parts[1]);
  if (!Number.isInteger(iterations) || iterations <= 0) return false;
  const saltBytes = hexToBytes(parts[2]);
  const expectedHashHex = parts[3];
  const candidateHashHex = await pbkdf2Hex(password, saltBytes, iterations);
  return timingSafeEqual(candidateHashHex, expectedHashHex);
}
